const now = new Date();
const daysAgo = (days) => new Date(now.getTime() - days * 86400000).toISOString().slice(0, 19).replace('T', ' ');

const users = [
  {
    id: 1,
    username: 'demo_admin',
    email: 'demo-admin@example.com',
    role: 'admin',
    accessible_views: '[]',
    whatsapp_instance_id: 'demo-admin',
    created_at: daysAgo(40),
  },
  {
    id: 2,
    username: 'demo_comercial',
    email: 'demo-comercial@example.com',
    role: 'comercial_pro',
    accessible_views: '[]',
    whatsapp_instance_id: 'demo-comercial',
    created_at: daysAgo(28),
  },
];

const places = [
  {
    id: 101,
    name: 'Clínica Dental Avenida',
    main_category: 'Clínica dental',
    raw_categories: 'Dentista, Salud',
    tags: 'salud, alta prioridad',
    notes: 'Demo: negocio local con web antigua.',
    place_id: 'demo-place-101',
    phone: '+34 910 111 201',
    phone_type: 'mobile',
    web: 'https://clinicadentalavenida.example',
    street_address: 'Calle Mayor 12',
    city: 'Madrid',
    barrio: 'Centro',
    zip: '28013',
    state: 'Madrid',
    country_code: 'ES',
    latitude: 40.4168,
    longitude: -3.7038,
    source_query: 'dentistas Madrid centro',
    lead_id: null,
    user_id: 1,
    job_id: 301,
    created_at: daysAgo(2),
    deleted_at: null,
  },
  {
    id: 102,
    name: 'Restaurante La Plaza',
    main_category: 'Restaurante',
    raw_categories: 'Restaurante mediterráneo',
    tags: 'hostelería, sin web',
    notes: 'Demo: solo redes sociales.',
    place_id: 'demo-place-102',
    phone: '+34 910 111 202',
    phone_type: 'landline',
    web: 'https://instagram.com/laplaza-demo',
    street_address: 'Plaza Nueva 4',
    city: 'Sevilla',
    barrio: 'Santa Cruz',
    zip: '41004',
    state: 'Sevilla',
    country_code: 'ES',
    latitude: 37.3891,
    longitude: -5.9845,
    source_query: 'restaurantes Sevilla',
    lead_id: null,
    user_id: 2,
    job_id: 302,
    created_at: daysAgo(4),
    deleted_at: null,
  },
  {
    id: 103,
    name: 'Gimnasio Norte Fit',
    main_category: 'Gimnasio',
    raw_categories: 'Fitness, Entrenador personal',
    tags: 'fitness, sin web',
    notes: 'Demo: buen candidato para landing.',
    place_id: 'demo-place-103',
    phone: '+34 910 111 203',
    phone_type: 'mobile',
    web: '',
    street_address: 'Avenida del Norte 88',
    city: 'Valencia',
    barrio: 'Benimaclet',
    zip: '46020',
    state: 'Valencia',
    country_code: 'ES',
    latitude: 39.4699,
    longitude: -0.3763,
    source_query: 'gimnasios Valencia',
    lead_id: 201,
    user_id: 1,
    job_id: 303,
    created_at: daysAgo(7),
    deleted_at: null,
  },
  {
    id: 104,
    name: 'Floristería El Jardín',
    main_category: 'Floristería',
    raw_categories: 'Tienda de flores',
    tags: 'retail, temporada',
    notes: 'Demo: web no responsive.',
    place_id: 'demo-place-104',
    phone: '+34 910 111 204',
    phone_type: 'landline',
    web: 'https://floristeriaeljardin.example',
    street_address: 'Carrer de Mallorca 21',
    city: 'Barcelona',
    barrio: 'Eixample',
    zip: '08029',
    state: 'Barcelona',
    country_code: 'ES',
    latitude: 41.3874,
    longitude: 2.1686,
    source_query: 'floristerías Barcelona',
    lead_id: 202,
    user_id: 2,
    job_id: 304,
    created_at: daysAgo(10),
    deleted_at: null,
  },
];

const leads = [
  {
    id: 201,
    user_id: 1,
    full_name: 'Gimnasio Norte Fit',
    email: 'hola@nortefit.example',
    phone: '+34 910 111 203',
    city: 'Valencia',
    barrio: 'Benimaclet',
    phone_type: 'mobile',
    source: 'scraper',
    status: 'new',
    notes: 'Demo: interesado en mejorar captación de socios.',
    assigned_to: 2,
    assigned_username: 'demo_comercial',
    estimated_value: 1200,
    estimated_benefit: 420,
    contact_method: 'whatsapp',
    tags: 'fitness, sin web',
    web: '',
    preview_delivery_date: daysAgo(-2),
    created_at: daysAgo(6),
    deleted_at: null,
  },
  {
    id: 202,
    user_id: 2,
    full_name: 'Floristería El Jardín',
    email: 'contacto@eljardin.example',
    phone: '+34 910 111 204',
    city: 'Barcelona',
    barrio: 'Eixample',
    phone_type: 'landline',
    source: 'manual',
    status: 'contacted',
    notes: 'Demo: se envió propuesta inicial.',
    assigned_to: 2,
    assigned_username: 'demo_comercial',
    estimated_value: 900,
    estimated_benefit: 310,
    contact_method: 'email',
    tags: 'retail, temporada',
    web: 'https://floristeriaeljardin.example',
    preview_delivery_date: daysAgo(3),
    created_at: daysAgo(9),
    deleted_at: null,
  },
  {
    id: 203,
    user_id: 1,
    full_name: 'Clínica Dental Avenida',
    email: '',
    phone: '+34 910 111 201',
    city: 'Madrid',
    barrio: 'Centro',
    phone_type: 'mobile',
    source: 'scraper',
    status: 'interested',
    notes: 'Demo: pidió ejemplos de webs clínicas.',
    assigned_to: 1,
    assigned_username: 'demo_admin',
    estimated_value: 1600,
    estimated_benefit: 560,
    contact_method: 'phone',
    tags: 'salud, alta prioridad',
    web: 'https://clinicadentalavenida.example',
    preview_delivery_date: daysAgo(-5),
    created_at: daysAgo(3),
    deleted_at: null,
  },
];

const jobs = [
  { id: 301, query: 'dentistas Madrid centro', status: 'completed', total_results: 18, inserted: 12, updated: 3, user_id: 1, created_at: daysAgo(2) },
  { id: 302, query: 'restaurantes Sevilla', status: 'completed', total_results: 24, inserted: 15, updated: 4, user_id: 2, created_at: daysAgo(4) },
  { id: 303, query: 'gimnasios Valencia', status: 'completed', total_results: 11, inserted: 8, updated: 1, user_id: 1, created_at: daysAgo(7) },
];

const leadActions = [
  { id: 1, lead_id: 201, user_id: 2, username: 'demo_comercial', action_type: 'created', action_description: 'Lead demo creado desde place', old_value: null, new_value: null, created_at: daysAgo(6) },
  { id: 2, lead_id: 202, user_id: 2, username: 'demo_comercial', action_type: 'updated_status', action_description: 'status actualizado', old_value: 'new', new_value: 'contacted', created_at: daysAgo(8) },
  { id: 3, lead_id: 203, user_id: 1, username: 'demo_admin', action_type: 'updated_status', action_description: 'status actualizado', old_value: 'contacted', new_value: 'interested', created_at: daysAgo(2) },
];

const whatsappMessages = [
  { id: 1, lead_id: 201, direction: 'outbound', body: 'Hola, te escribo sobre vuestra presencia online.', created_at: daysAgo(5) },
  { id: 2, lead_id: 201, direction: 'inbound', body: 'Gracias, envíame más información.', created_at: daysAgo(4) },
  { id: 3, lead_id: 203, direction: 'inbound', body: 'Nos interesa ver una demo para clínica dental.', created_at: daysAgo(2) },
];

const funnel = {
  201: { lead_id: 201, current_phase: 2, phase1_completed: true, phase2_completed: false, phase3_completed: false, phase4_completed: false },
  203: { lead_id: 203, current_phase: 3, phase1_completed: true, phase2_completed: true, phase3_completed: false, phase4_completed: false },
};

module.exports = {
  users,
  places,
  leads,
  jobs,
  leadActions,
  whatsappMessages,
  funnel,
};
